name: Overwhisper
options:
  bundleIdPrefix: com.overseed
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    ENABLE_HARDENED_RUNTIME: YES
    SWIFT_VERSION: "5.9"

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit.git
    from: "0.9.0"
  HotKey:
    url: https://github.com/soffes/HotKey.git
    from: "0.2.0"

targets:
  Overwhisper:
    type: application
    platform: macOS
    sources:
      - path: Overwhisper
        excludes:
          - "**/*.entitlements"
          - "**/Info.plist"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.overseed.overwhisper
        INFOPLIST_FILE: Overwhisper/Info.plist
        CODE_SIGN_ENTITLEMENTS: Overwhisper/Overwhisper.entitlements
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "-"
        Release:
          CODE_SIGN_IDENTITY: "Apple Development"
    dependencies:
      - package: WhisperKit
      - package: HotKey
    info:
      path: Overwhisper/Info.plist
    entitlements:
      path: Overwhisper/Overwhisper.entitlements

schemes:
  Overwhisper:
    build:
      targets:
        Overwhisper: all
    run:
      config: Debug
    archive:
      config: Release
